### ISSUE TITLE
Incompatible NumPy version

### ISSUE THREAD

**Issue by sean-workman** [Finn-Lab/SanntiS#9] opened 2024-07-25 19:10 UTC
I am having trouble with getting SanntiS to run properly while following the install instructions in the README.

I have downloaded InterProScan and set it up following their directions on the ReadTheDocs. I ensured that the IPS directory was added to my path. The IPS steps run just fine.

When I run any command with SanntiS (e.g. `sanntis --help`), I get the expected usage information output but I also see this:

`/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py:61: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 1.19.5)
  from scipy import sparse as scipy_sparse  # pylint: disable=g-import-not-at-top`

When I do end up running the SanntiS pipeline I use the command:

`sanntis --meta False --outdir sanntis --cpu 15 wt_polished.fasta`

It looks to run okay but then I see this Python error:

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/sanntis/bin/sanntis", line 10, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/sanntis/_cli.py", line 166, in main
    annotate = AnnotationFilesToEmerald()
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/sanntis/modules/BGCdetection.py", line 49, in __init__
    self.vocab, self.typeModel, self.mbdoms = pickle.load(h)
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/sklearn/utils/__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/scipy/sparse/__init__.py", line 294, in <module>
    from ._base import *
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/scipy/sparse/_base.py", line 5, in <module>
    from scipy._lib._util import VisibleDeprecationWarning
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/scipy/_lib/_util.py", line 18, in <module>
    from scipy._lib._array_api import array_namespace
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/scipy/_lib/_array_api.py", line 17, in <module>
    from scipy._lib.array_api_compat import (
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/scipy/_lib/array_api_compat/numpy/__init__.py", line 16, in <module>
    __import__(__package__ + '.linalg')
  File "/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/scipy/_lib/array_api_compat/numpy/linalg.py", line 2, in <module>
    from numpy.linalg import __all__ as linalg_all
ImportError: cannot import name '__all__' from 'numpy.linalg' (/opt/miniconda3/envs/sanntis/lib/python3.9/site-packages/numpy/linalg/__init__.py)
```

Can you give me some suggestions on what I can do to solve this?

**Comment by SantiagoSanchezF** [comment] 2024-08-01 15:08
Hi Sean,

Thank you for bringing this issue to my attention.

I could replicate the problem.

It seems that the problem is related to a version mismatch between scipy and numpy. The error you're encountering can be resolved by updating scipy to version 1.7.3, which is compatible with the other SanntiS dependencies.

To fix this, you can run the following command:

```bash
conda install scipy=1.7.3
```

This should resolve the error and allow SanntiS to run.

I'm currently working on making this fix propagate to the Bioconda installation to prevent this issue from happening in the future. In the meantime, the above command should do the trick.

Please let me know if you have any further issues or need more details, and thanks again for your patience!

**Comment by sean-workman** [comment] 2024-08-01 15:55
Hi Santiago,

Thanks for checking on this. I thought to try changing my NumPy version to something >1.22 and the conda solver failed - I didn't think to try changing the SciPy version. I will do this now!

No need to thank me for patience, this is FOSS, you don't owe me anything! :)

**Comment by SantiagoSanchezF** [comment] 2024-08-02 09:06
Hi Sean,

Changes are now reflected in bioconda.

Thanks!

**Closed as completed by SantiagoSanchezF** 2024-08-02 09:06 UTC
